### PR TITLE
Fixed all errors, and fixed log.error depreciated warnings.

### PR DESCRIPTION
**Pull request by dekeche**
HairDef.hairGender is no longer valid. Changed to new styleGender (also enum HairGender to StyleGender).
Added portrait direction (Rot4.South) to PortraitsCache.Get calls.
updated GatheringsUtility.ShouldPawnKeepGathering.
Updated previous string lists with correct objects, from alienRaceDef changes.
Updated DroidUtility DoTend to match current function.

Following changes may need testing:
MpteMaker changed to FleckMaker, and relevant ThingDefOf changed to related FleckDefOf.
GizmoRenderParms added to GizmoOnGUI calls, so it now overrides the new function.
Vector2 scrollPosition changed to ThingFilterUI.UIState

Did not commit changes to .csproj or obj/debug files.

### CODE REVIEW

**Comment by dekeche** [comment]
Everything builds fine, but the xml files will still need to be updated.

**Comment by BlueBackbite** [comment]
Just a heads up that when I built this, printers are still throwing errors when trying to open the print window/dev mode on. And I've been trying to track down the xml changes.

**Comment by AppleConnoiseur** [comment]
Good job! Merged!

**Comment by dekeche** [comment]
@BlueBackbite
That's odd, did you update the build path? I didn't commit any changes to the .csproj file, so if you didn't change the build path to 1.3 and already created that folder, you'd probably still throw the original errors.
Just re-tested on my end, using god mode to build everything and debug print, no errors.


Reason I didn't commit the changes is that I've apparently stored the androids source folder in a completely different location, so I had to re-write all the dependency path information. Figured it wouldn't be a good idea to mess up everyone else's setup.

**Comment by BlueBackbite** [comment]
@dekeche it had to have been something I did/misconfigured... thanks for putting the work into this!

**Pull request merged**
